### ISSUE TITLE
self.swizzledLayoutSubviews() crashed

### ISSUE THREAD

**Issue by manaes** [MaximKotliar/Bartinter#5]
How to make "Modal View Present" also working?

when some view controller present - dismiss action, crashed!

@objc func swizzledLayoutSubviews() {
    self.swizzledLayoutSubviews() <--- here
    ...
}

<img width="530" alt="2018-07-13_09-35-43" src="https://user-images.githubusercontent.com/1999314/42666458-368286b6-8680-11e8-9bb0-a462f23888e1.png">

**Comment by MaximKotliar** [comment]
Please specify device and iOS version, or if you can - make a sample project, i will take a look.

**Comment by BertrandVillain** [comment]
I experiment troubles in the same line codes (infinite loop with a white frozen screen and memory leaks)

To give you more details, I can tell you it happens only when using “zoomed” display
(display&brightness -> display zoom)

I can’t share you the code as it’s a private company project

Thank you

**Comment by MaximKotliar** [comment]
@loliloler Thanks for details, I will take a look. As temporary workaround, you can try disable swizzling and update bartinter manually.

**Comment by MaximKotliar** [comment]
Hey @loliloler, I've tried to reproduce issue on iOS 10, 11, 12 in zoom mode, and have no luck. Can you please provide list of pods in your project?

**Comment by BertrandVillain** [comment]
SVProgressHUD
Marshal
Kingfisher
SwiftSpringBoard

Other pods are private company repo (geoloc)

Thank you for your time

**Comment by MaximKotliar** [comment]
Closing issue. Not reproduced.
