### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by SanaAhmed** [MaximKotliar/Bartinter#7]
I am getting the following error on pod install

Analyzing dependencies
[!] Unable to find a specification for `Bartinter`

if I add version
[!] Unable to find a specification for `Bartinter (~> 0.0.3)`

Tried both for 
platform :ios, '9.0'
and
platform :ios, '10.2'

**Comment by MaximKotliar** [comment]
Have you run ```pod repo update``` ?

**Comment by SanaAhmed** [comment]
Thanks that resolves it
