### ISSUE TITLE
UIGraphicsGetImageFromCurrentImageContext Crash

### ISSUE THREAD

**Issue by GLJeffery** [MaximKotliar/Bartinter#9]
I'm getting a crash on the following line
let image = UIGraphicsGetImageFromCurrentImageContext() 

It happens rarely but I'm wondering if it happens since it's background thread running some mainthread-like functions, any thoughts?

EXC_BAD_ACCESS
Rogue memory write has corrupted memory.

closure #1 in Bartinter.calculateStatusBarAreaAvgLuminance(_:)

    private func calculateStatusBarAreaAvgLuminance(_ completion: @escaping (CGFloat) -> Void) {
        let scale: CGFloat = 0.5
        let size = UIApplication.shared.statusBarFrame.size
        throttler.throttle { [weak self] in
            guard let strongLayer = self?.parent?.view.layer else { return }
            UIGraphicsBeginImageContextWithOptions(size, false, scale)
            guard let context = UIGraphicsGetCurrentContext() else { return }
            strongLayer.render(in: context) <--- crashes
            let image = UIGraphicsGetImageFromCurrentImageContext()
            guard let averageLuminance = image?.averageLuminance else { return }
            UIGraphicsEndImageContext()
            DispatchQueue.main.async {
                completion(averageLuminance)
            }
        }
    }

**Comment by MaximKotliar** [comment]
Hey. Please update Bartinter to version 0.0.4 and let me know if issue stay.

**Comment by UIApplicationMain** [comment]
~~Hey Maxim (above is my other account), I am on 0.0.4 already, the issue that was fixed was in the same code block but slightly different.~~

~~I think it may have to do with running render in background thread vs main thread.~~

~~We have this in our app at large scale so it is still happening, but hard to reproduce.~~

EDIT:

Actually I am wrong, @MaximKotliar I am using 0.0.3 still, I will update to 0.0.4 and let you know if this error still exists.

**Comment by GLJeffery** [comment]
I am going to close this issue until I have a chance to tackle it, thanks for the fast replies @MaximKotliar !

**Comment by xradeon** [comment]
Can confirm this bug is alive on 0.0.4.

```
Crashed: com.apple.root.background-qos
0  WebCore                        0x19ebf33c4 _WebThreadLock() + 348
1  WebCore                        0x19ebf4138 WebThreadLock + 104
2  UIKitCore                      0x1c3635a78 -[UIWebTiledView layoutSubviews] + 52
3  UIKitCore                      0x1c360d33c -[UIWebDocumentView layoutSubviews] + 164
4  UIKitCore                      0x1c35c177c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1380
5  QuartzCore                     0x19a3f5b7c -[CALayer layoutSublayers] + 184
6  QuartzCore                     0x19a3fab34 CA::Layer::layout_if_needed(CA::Transaction*) + 324
7  QuartzCore                     0x19a3f5a98 -[CALayer layoutIfNeeded] + 252
8  QuartzCore                     0x19a3f2dfc -[CALayer renderInContext:] + 168
9  Bartinter                      0x104f8b0b8 closure #1 in closure #1 in Bartinter.calculateStatusBarAreaAvgLuminance(_:) (Bartinter.swift:75)
10 Bartinter                      0x104f8d7e4 partial apply for closure #1 in Throttler.throttle(_:) (<compiler-generated>)
11 Bartinter                      0x104f8dc8c thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
12 libdispatch.dylib              0x1957df198 _dispatch_block_async_invoke2 + 104
13 libdispatch.dylib              0x195832484 _dispatch_client_callout + 16
14 libdispatch.dylib              0x1957d582c _dispatch_continuation_pop$VARIANT$mp + 412
15 libdispatch.dylib              0x1957e5b9c _dispatch_source_invoke$VARIANT$mp + 1704
16 libdispatch.dylib              0x1957e1a18 _dispatch_root_queue_drain + 376
17 libdispatch.dylib              0x1957e22c0 _dispatch_worker_thread2 + 128
18 libsystem_pthread.dylib        0x195a1517c _pthread_wqthread + 472
19 libsystem_pthread.dylib        0x195a17cec start_wqthread + 4
```
